services:
  anubis:
    image: ghcr.io/techarohq/anubis:latest
    environment:
      TARGET: http://web:8080
    labels:
      caddy: dev.tawmy.dev
      caddy.reverse_proxy: "{{upstreams 3000}}"
  
  web:
    image: ghcr.io/tawmy/tawmy.dev:main
    networks:
      - reverse-proxy
    volumes:
      - /root/tawmy.dev/data:/mnt/data

networks:
  reverse-proxy:
    external: true