services:
  web:
    networks:
      - caddy
    labels:
      caddy: dev.tawmy.dev
      caddy.reverse_proxy: "{{upstreams 8080}}"
    volumes:
      - /root/tawmy.dev/data:/mnt/data

networks:
  caddy:
    external: true